extern const GeoLayout gf_area_1_geo[];
extern const GeoLayout gf_area_1[];
extern const Collision gf_area_1_collision[];
extern const MacroObject gf_area_1_macro_objs[];
extern const GeoLayout gf_area_2_geo[];
extern const GeoLayout gf_area_2[];
extern const Collision gf_area_2_collision[];
extern const MacroObject gf_area_2_macro_objs[];
extern const GeoLayout gf_area_3_geo[];
extern const GeoLayout gf_area_3[];
extern const Collision gf_area_3_collision[];
extern const MacroObject gf_area_3_macro_objs[];
extern const GeoLayout gf_area_4_geo[];
extern const GeoLayout gf_area_4[];
extern const Collision gf_area_4_collision[];
extern const MacroObject gf_area_4_macro_objs[];
extern Vtx gf_dl_a1_mesh_layer_1_vtx_0[24];
extern Gfx gf_dl_a1_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_001_mesh_layer_1_vtx_0[9];
extern Gfx gf_dl_a1_001_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_002_mesh_layer_1_vtx_0[24];
extern Gfx gf_dl_a1_002_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_005_mesh_layer_1_vtx_0[9];
extern Gfx gf_dl_a1_005_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_003_mesh_layer_1_vtx_0[24];
extern Gfx gf_dl_a1_003_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_006_mesh_layer_1_vtx_0[9];
extern Gfx gf_dl_a1_006_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_004_mesh_layer_1_vtx_0[24];
extern Gfx gf_dl_a1_004_mesh_layer_1_tri_0[];
extern Vtx gf_dl_a1_007_mesh_layer_1_vtx_0[9];
extern Gfx gf_dl_a1_007_mesh_layer_1_tri_0[];
extern Gfx mat_gf_dl_f3dlite_material[];
extern Gfx mat_revert_gf_dl_f3dlite_material[];
extern Gfx gf_dl_a1_mesh_layer_1[];
extern Gfx gf_dl_a1_001_mesh_layer_1[];
extern Gfx gf_dl_a1_002_mesh_layer_1[];
extern Gfx gf_dl_a1_005_mesh_layer_1[];
extern Gfx gf_dl_a1_003_mesh_layer_1[];
extern Gfx gf_dl_a1_006_mesh_layer_1[];
extern Gfx gf_dl_a1_004_mesh_layer_1[];
extern Gfx gf_dl_a1_007_mesh_layer_1[];
