extern const GeoLayout gf_area_1_geo[];
extern const GeoLayout gf_area_1[];
extern const Collision gf_area_1_collision[];
extern const MacroObject gf_area_1_macro_objs[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Loop[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Rail[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Rail_001[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Rail_006[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Rail_007[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Rail_008[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_001[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_002[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_003[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_004[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_005[];
extern const Trajectory gf_area_1_spline_NurbsCurve_Spring_015[];
extern const GeoLayout gf_area_2_geo[];
extern const GeoLayout gf_area_2[];
extern const Collision gf_area_2_collision[];
extern const MacroObject gf_area_2_macro_objs[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Loop_001[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Loop_002[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Loop_003[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Rail_002[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Rail_003[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Rail_004[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Rail_009[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Spring_006[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Spring_007[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Spring_008[];
extern const Trajectory gf_area_2_spline_NurbsCurve_Spring_009[];
extern const Trajectory gf_area_2_spline_NurbsCurve_VineLoop_005[];
extern const GeoLayout gf_area_3_geo[];
extern const GeoLayout gf_area_3[];
extern const Collision gf_area_3_collision[];
extern const MacroObject gf_area_3_macro_objs[];
extern const Trajectory gf_area_3_spline_NurbsCurve_Spring_010[];
extern const Trajectory gf_area_3_spline_NurbsCurve_Spring_011[];
extern const Trajectory gf_area_3_spline_NurbsCurve_Spring_012[];
extern const Trajectory gf_area_3_spline_NurbsCurve_Spring_013[];
extern const Trajectory gf_area_3_spline_NurbsCurve_Spring_014[];
extern const GeoLayout gf_area_4_geo[];
extern const GeoLayout gf_area_4[];
extern const Collision gf_area_4_collision[];
extern const MacroObject gf_area_4_macro_objs[];
extern const Trajectory gf_area_4_spline_NurbsCurve_Loop_004[];
extern const Trajectory gf_area_4_spline_NurbsCurve_Loop_005[];
extern const Trajectory gf_area_4_spline_NurbsCurve_Spring_016[];
extern Vtx gf_dl_a1_mesh_layer_1_vtx_0[24];
extern Vtx gf_dl_a1_001_mesh_layer_1_vtx_0[9];
extern Vtx gf_dl_C_object_00C6F038_mesh_layer_1_vtx_0[8];
extern Vtx gf_dl_a1_002_mesh_layer_1_vtx_0[24];
extern Vtx gf_dl_a1_005_mesh_layer_1_vtx_0[9];
extern Vtx gf_dl_C_object_00C6EB00_mesh_layer_1_vtx_0[8];
extern Vtx gf_dl_C_object_00C6FDB8_mesh_layer_1_vtx_0[12];
extern Vtx gf_dl_C_object_00C726A0_mesh_layer_1_vtx_0[8];
extern Vtx gf_dl_object_00C73774_mesh_layer_1_vtx_0[13];
extern Vtx gf_dl_object_00C739E4_mesh_layer_1_vtx_0[17];
extern Vtx gf_dl_a1_003_mesh_layer_1_vtx_0[24];
extern Vtx gf_dl_a1_006_mesh_layer_1_vtx_0[9];
extern Vtx gf_dl_a1_004_mesh_layer_1_vtx_0[24];
extern Vtx gf_dl_a1_007_mesh_layer_1_vtx_0[9];
extern Gfx gf_dl_a1_mesh_layer_1[];
extern Gfx gf_dl_a1_001_mesh_layer_1[];
extern Gfx gf_dl_C_object_00C6F038_mesh_layer_1[];
extern Gfx gf_dl_a1_002_mesh_layer_1[];
extern Gfx gf_dl_a1_005_mesh_layer_1[];
extern Gfx gf_dl_C_object_00C6EB00_mesh_layer_1[];
extern Gfx gf_dl_C_object_00C6FDB8_mesh_layer_1[];
extern Gfx gf_dl_C_object_00C726A0_mesh_layer_1[];
extern Gfx gf_dl_object_00C73774_mesh_layer_1[];
extern Gfx gf_dl_object_00C739E4_mesh_layer_1[];
extern Gfx gf_dl_a1_003_mesh_layer_1[];
extern Gfx gf_dl_a1_006_mesh_layer_1[];
extern Gfx gf_dl_a1_004_mesh_layer_1[];
extern Gfx gf_dl_a1_007_mesh_layer_1[];
