typedef enum LevelConv_PlainLevels
{
    LevelConv_PlainLevels_OFF,
    LevelConv_PlainLevels_H_C1,
    LevelConv_PlainLevels_H_C2,
    LevelConv_PlainLevels_H_C3,
    LevelConv_PlainLevels_H_C4,
    LevelConv_PlainLevels_H_C5,
    LevelConv_PlainLevels_H_C6,
    LevelConv_PlainLevels_H_C7,
    LevelConv_PlainLevels_H_C8,
    LevelConv_PlainLevels_H_C9,
    LevelConv_PlainLevels_H_C10,
    LevelConv_PlainLevels_H_C11,
    LevelConv_PlainLevels_H_C12,
    LevelConv_PlainLevels_H_C13,
    LevelConv_PlainLevels_H_C14,
    LevelConv_PlainLevels_H_C15,
    
    LevelConv_PlainLevels_D_C1,
    LevelConv_PlainLevels_D_C2,
    LevelConv_PlainLevels_D_C3,
    LevelConv_PlainLevels_D_C4,
    LevelConv_PlainLevels_D_C5,
    LevelConv_PlainLevels_D_C6,
    LevelConv_PlainLevels_D_C7,
    LevelConv_PlainLevels_D_C8,
    LevelConv_PlainLevels_D_C9,
    LevelConv_PlainLevels_D_C10,
    LevelConv_PlainLevels_D_C11,
    LevelConv_PlainLevels_D_C12,
    LevelConv_PlainLevels_D_C13,
} LevelConv_PlainLevels;

int LevelConv_toSM64Level(LevelConv_PlainLevels);
