extern const GeoLayout dc_sandglass_sandf_geo[];
extern u8 dc_sandglass_sandf_dz_sandglass_sand64_ci4[];
extern u8 dc_sandglass_sandf_dz_sandglass_sand64_pal_rgba16[];
extern Vtx dc_sandglass_sandf_dc_sandglass_sandf_mesh_layer_1_vtx_0[5];
extern Gfx dc_sandglass_sandf_dc_sandglass_sandf_mesh_layer_1_tri_0[];
extern Gfx mat_dc_sandglass_sandf_SANDGLASS_SANDF_sa2mdl_0_f3d[];
extern Gfx mat_revert_dc_sandglass_sandf_SANDGLASS_SANDF_sa2mdl_0_f3d[];
extern Gfx dc_sandglass_sandf_dc_sandglass_sandf_mesh_layer_1[];
