extern const GeoLayout wb_shut_geo[];
extern u8 wb_shut_miu128_wb002_ci4[];
extern u8 wb_shut_miu128_wb002_pal_rgba16[];
extern u8 wb_shut_miu64_wb002_ci4[];
extern u8 wb_shut_miu64_wb002_pal_rgba16[];
extern Vtx wb_shut_wb_shut_mesh_layer_1_vtx_0[12];
extern Gfx wb_shut_wb_shut_mesh_layer_1_tri_0[];
extern Vtx wb_shut_wb_shut_mesh_layer_6_vtx_0[4];
extern Gfx wb_shut_wb_shut_mesh_layer_6_tri_0[];
extern Gfx mat_wb_shut_SHUT_sa2bmdl_0_f3d[];
extern Gfx mat_revert_wb_shut_SHUT_sa2bmdl_0_f3d[];
extern Gfx mat_wb_shut_SHUT_sa2bmdl_1_f3d[];
extern Gfx mat_revert_wb_shut_SHUT_sa2bmdl_1_f3d[];
extern Gfx wb_shut_wb_shut_mesh_layer_1[];
extern Gfx wb_shut_wb_shut_mesh_layer_6[];
