extern const GeoLayout rh_area_1_geo[];
extern const GeoLayout rh_area_1[];
extern const Collision rh_area_1_collision[];
extern const MacroObject rh_area_1_macro_objs[];
extern const Trajectory rh_area_1_spline_Loop_NurbsCurve[];
extern const Trajectory rh_area_1_spline_Loop_NurbsCurve_001[];
extern const Trajectory rh_area_1_spline_Rail_NurbsCurve[];
extern const Trajectory rh_area_1_spline_Rail_NurbsCurve_001[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_001[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_002[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_003[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_012[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_013[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_014[];
extern const Trajectory rh_area_1_spline_Spring_NurbsCurve_015[];
extern const GeoLayout rh_area_2_geo[];
extern const GeoLayout rh_area_2[];
extern const Collision rh_area_2_collision[];
extern const MacroObject rh_area_2_macro_objs[];
extern const Trajectory rh_area_2_spline_Loop_NurbsCurve_002[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_004[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_005[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_006[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_007[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_008[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_009[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_010[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_011[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_016[];
extern const Trajectory rh_area_2_spline_Spring_NurbsCurve_017[];
extern const GeoLayout rh_area_3_geo[];
extern const GeoLayout rh_area_3[];
extern const Collision rh_area_3_collision[];
extern const MacroObject rh_area_3_macro_objs[];
extern const Trajectory rh_area_3_spline_Loop_NurbsCurve_007[];
extern const Trajectory rh_area_3_spline_Loop_NurbsCurve_008[];
extern const Trajectory rh_area_3_spline_Rail_NurbsCurve_002[];
extern const Trajectory rh_area_3_spline_Rail_NurbsCurve_003[];
extern const Trajectory rh_area_3_spline_Rail_NurbsCurve_004[];
extern const Trajectory rh_area_3_spline_Rail_NurbsCurve_005[];
extern const Trajectory rh_area_3_spline_Spring_NurbsCurve_022[];
extern const Trajectory rh_area_3_spline_Spring_NurbsCurve_023[];
extern const Trajectory rh_area_3_spline_Spring_NurbsCurve_024[];
extern const GeoLayout rh_area_4_geo[];
extern const GeoLayout rh_area_4[];
extern const Collision rh_area_4_collision[];
extern const MacroObject rh_area_4_macro_objs[];
extern const Trajectory rh_area_4_spline_Rail_NurbsCurve_006[];
extern const Trajectory rh_area_4_spline_Rail_NurbsCurve_007[];
extern const Trajectory rh_area_4_spline_Rail_NurbsCurve_008[];
extern const Trajectory rh_area_4_spline_Rail_NurbsCurve_009[];
extern const GeoLayout rh_area_5_geo[];
extern const GeoLayout rh_area_5[];
extern const Collision rh_area_5_collision[];
extern const MacroObject rh_area_5_macro_objs[];
extern const GeoLayout rh_area_6_geo[];
extern const GeoLayout rh_area_6[];
extern const Collision rh_area_6_collision[];
extern const MacroObject rh_area_6_macro_objs[];
extern const Trajectory rh_area_6_spline_Loop_NurbsCurve_003[];
extern const Trajectory rh_area_6_spline_Loop_NurbsCurve_004[];
extern const Trajectory rh_area_6_spline_Loop_NurbsCurve_005[];
extern const Trajectory rh_area_6_spline_Loop_NurbsCurve_006[];
extern const Trajectory rh_area_6_spline_Spring_NurbsCurve_018[];
extern const Trajectory rh_area_6_spline_Spring_NurbsCurve_019[];
extern const Trajectory rh_area_6_spline_Spring_NurbsCurve_020[];
extern const GeoLayout rh_area_7_geo[];
extern const GeoLayout rh_area_7[];
extern const Collision rh_area_7_collision[];
extern const MacroObject rh_area_7_macro_objs[];
extern const Trajectory rh_area_7_spline_Spring_NurbsCurve_021[];
extern u8 rh_dl_miu128_ce009_ci4[];
extern u8 rh_dl_miu128_ce009_pal_rgba16[];
extern Vtx rh_dl_a3_001_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_001_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_008_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_008_mesh_layer_5_tri_0[];
extern Vtx rh_dl_object_0116E340_mesh_layer_1_vtx_0[12];
extern Gfx rh_dl_object_0116E340_mesh_layer_1_tri_0[];
extern Vtx rh_dl_a3_002_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_002_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_009_mesh_layer_5_vtx_0[25];
extern Gfx rh_dl_a3_009_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_003_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_003_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_010_mesh_layer_5_vtx_0[25];
extern Gfx rh_dl_a3_010_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_004_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_004_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_011_mesh_layer_5_vtx_0[25];
extern Gfx rh_dl_a3_011_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_005_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_005_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_012_mesh_layer_5_vtx_0[12];
extern Gfx rh_dl_a3_012_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_006_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_006_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_013_mesh_layer_5_vtx_0[27];
extern Gfx rh_dl_a3_013_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_007_mesh_layer_5_vtx_0[24];
extern Gfx rh_dl_a3_007_mesh_layer_5_tri_0[];
extern Vtx rh_dl_a3_014_mesh_layer_5_vtx_0[12];
extern Gfx rh_dl_a3_014_mesh_layer_5_tri_0[];
extern Gfx mat_rh_dl_f3dlite_material_002[];
extern Gfx mat_revert_rh_dl_f3dlite_material_002[];
extern Gfx mat_rh_dl_HAMMER2_sa1mdl_0_f3d[];
extern Gfx mat_revert_rh_dl_HAMMER2_sa1mdl_0_f3d[];
extern Gfx rh_dl_a3_001_mesh_layer_5[];
extern Gfx rh_dl_a3_008_mesh_layer_5[];
extern Gfx rh_dl_object_0116E340_mesh_layer_1[];
extern Gfx rh_dl_a3_002_mesh_layer_5[];
extern Gfx rh_dl_a3_009_mesh_layer_5[];
extern Gfx rh_dl_a3_003_mesh_layer_5[];
extern Gfx rh_dl_a3_010_mesh_layer_5[];
extern Gfx rh_dl_a3_004_mesh_layer_5[];
extern Gfx rh_dl_a3_011_mesh_layer_5[];
extern Gfx rh_dl_a3_005_mesh_layer_5[];
extern Gfx rh_dl_a3_012_mesh_layer_5[];
extern Gfx rh_dl_a3_006_mesh_layer_5[];
extern Gfx rh_dl_a3_013_mesh_layer_5[];
extern Gfx rh_dl_a3_007_mesh_layer_5[];
extern Gfx rh_dl_a3_014_mesh_layer_5[];
