extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_Material_ia16[];
extern Vtx castle_grounds_dl_Untitled_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_mesh_layer_5_vtx_0[823];
extern Vtx castle_grounds_dl_Untitled_mesh_layer_5_vtx_1[496];
extern Vtx castle_grounds_dl_Untitled_002_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_002_mesh_layer_5_vtx_0[50];
extern Gfx castle_grounds_dl_Untitled_mesh_layer_5[];
extern Gfx castle_grounds_dl_Untitled_002_mesh_layer_5[];
