#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/castle_grounds/areas/1/movtext.inc.c"

#include "levels/castle_grounds/leveldata.inc.c"

#include "levels/castle_grounds/ow_ce/model.inc.c"
#include "levels/castle_grounds/ow_wc/model.inc.c"
#include "levels/castle_grounds/ow_pl/model.inc.c"
#include "levels/castle_grounds/ow_mh/model.inc.c"
#include "levels/castle_grounds/ow_gf/model.inc.c"
#include "levels/castle_grounds/ow_ph/model.inc.c"
#include "levels/castle_grounds/ow_ms/model.inc.c"
#include "levels/castle_grounds/ow_am/model.inc.c"
#include "levels/castle_grounds/ow_hb/model.inc.c"
#include "levels/castle_grounds/ow_pc/model.inc.c"
#include "levels/castle_grounds/ow_dc/model.inc.c"
#include "levels/castle_grounds/ow_ee/model.inc.c"
#include "levels/castle_grounds/ow_mhe/model.inc.c"
#include "levels/castle_grounds/ow_cg/model.inc.c"
#include "levels/castle_grounds/ow_fr/model.inc.c"