extern const GeoLayout pc_sandglass_spring_geo[];
extern u8 pc_sandglass_spring_dz_sandglass_buttan128_ci4[];
extern u8 pc_sandglass_spring_dz_sandglass_buttan128_pal_rgba16[];
extern u8 pc_sandglass_spring_dz_sandglass_body128_ci4[];
extern u8 pc_sandglass_spring_dz_sandglass_body128_pal_rgba16[];
extern Vtx pc_sandglass_spring_pc_sandglass_spring_mesh_layer_1_vtx_0[33];
extern Vtx pc_sandglass_spring_pc_sandglass_spring_mesh_layer_1_vtx_1[20];
extern Gfx pc_sandglass_spring_pc_sandglass_spring_mesh_layer_1[];
