extern const GeoLayout hb_block_geo[];
extern u8 hb_block_dz_hb_eggbox256_ci4[];
extern u8 hb_block_dz_hb_eggbox256_pal_rgba16[];
extern u8 hb_block_dz_hb_eggbox_up256_ci4[];
extern u8 hb_block_dz_hb_eggbox_up256_pal_rgba16[];
extern Vtx hb_block_hb_block_mesh_layer_1_vtx_0[16];
extern Gfx hb_block_hb_block_mesh_layer_1_tri_0[];
extern Vtx hb_block_hb_block_mesh_layer_1_vtx_1[4];
extern Gfx hb_block_hb_block_mesh_layer_1_tri_1[];
extern Gfx mat_hb_block_BLOCK_sa2mdl_0_002_f3d[];
extern Gfx mat_revert_hb_block_BLOCK_sa2mdl_0_002_f3d[];
extern Gfx mat_hb_block_BLOCK_sa2mdl_1_002_f3d[];
extern Gfx mat_revert_hb_block_BLOCK_sa2mdl_1_002_f3d[];
extern Gfx hb_block_hb_block_mesh_layer_1[];
