extern const GeoLayout gh_area_1_geo[];
extern const GeoLayout gh_area_1[];
extern const Collision gh_area_1_collision[];
extern const MacroObject gh_area_1_macro_objs[];
extern const GeoLayout gh_area_2_geo[];
extern const GeoLayout gh_area_2[];
extern const Collision gh_area_2_collision[];
extern const MacroObject gh_area_2_macro_objs[];
extern Vtx gh_dl_a3_001_mesh_layer_5_vtx_0[24];
extern Gfx gh_dl_a3_001_mesh_layer_5_tri_0[];
extern Vtx gh_dl_a3_002_mesh_layer_5_vtx_0[24];
extern Gfx gh_dl_a3_002_mesh_layer_5_tri_0[];
extern Vtx gh_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx gh_dl_Plane_mesh_layer_1_vtx_0[20];
extern Gfx gh_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_gh_dl_f3dlite_material_002[];
extern Gfx mat_revert_gh_dl_f3dlite_material_002[];
extern Gfx mat_gh_dl_f3dlite_material[];
extern Gfx mat_revert_gh_dl_f3dlite_material[];
extern Gfx gh_dl_a3_001_mesh_layer_5[];
extern Gfx gh_dl_a3_002_mesh_layer_5[];
extern Gfx gh_dl_Plane_mesh_layer_1[];
