extern const GeoLayout pc_sandglass_ends_geo[];
extern u8 pc_sandglass_ends_dz_sandglass_body128_ci4[];
extern u8 pc_sandglass_ends_dz_sandglass_body128_pal_rgba16[];
extern u8 pc_sandglass_ends_dz_sandglass_edge32_ci8[];
extern u8 pc_sandglass_ends_dz_sandglass_edge32_pal_rgba16[];
extern Vtx pc_sandglass_ends_pc_sandglass_ends_mesh_layer_1_vtx_0[12];
extern Vtx pc_sandglass_ends_pc_sandglass_ends_mesh_layer_1_vtx_1[100];
extern Vtx pc_sandglass_ends_pc_sandglass_ends_mesh_layer_1_vtx_2[126];
extern Gfx pc_sandglass_ends_pc_sandglass_ends_mesh_layer_1[];
