extern const GeoLayout mh_skybox_geo[];
extern u8 mh_skybox_prnbg8_1_rgba16[];
extern u8 mh_skybox_prnbg_2_rgba16[];
extern Vtx mh_skybox_mh_skybox_mesh_layer_1_vtx_cull[8];
extern Vtx mh_skybox_mh_skybox_mesh_layer_1_vtx_0[96];
extern Gfx mh_skybox_mh_skybox_mesh_layer_1_tri_0[];
extern Vtx mh_skybox_mh_skybox_mesh_layer_1_vtx_1[1056];
extern Gfx mh_skybox_mh_skybox_mesh_layer_1_tri_1[];
extern Gfx mat_mh_skybox_Skybox_sa2mdl_0_f3d[];
extern Gfx mat_revert_mh_skybox_Skybox_sa2mdl_0_f3d[];
extern Gfx mat_mh_skybox_Skybox_sa2mdl_1_f3d[];
extern Gfx mat_revert_mh_skybox_Skybox_sa2mdl_1_f3d[];
extern Gfx mh_skybox_mh_skybox_mesh_layer_1[];
