#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/dc/header.h"


#include "levels/dc/geo.inc.c"
#include "levels/dc/dc_door_b/geo.inc.c"
#include "levels/dc/dc_door_g/geo.inc.c"
#include "levels/dc/dc_door_n/geo.inc.c"
#include "levels/dc/dc_door_r/geo.inc.c"
#include "levels/dc/dc_box_blue/geo.inc.c"
#include "levels/dc/dc_box_blue_break/geo.inc.c"
#include "levels/dc/dc_box_green/geo.inc.c"
#include "levels/dc/dc_box_red/geo.inc.c"
#include "levels/dc/dc_box_green_break/geo.inc.c"
#include "levels/dc/dc_box_red_break/geo.inc.c"
#include "levels/dc/dc_treasure_blue/geo.inc.c"
#include "levels/dc/dc_treasure_green/geo.inc.c"
#include "levels/dc/dc_treasure_red/geo.inc.c"
#include "levels/dc/dc_treasure_blue_break/geo.inc.c"
#include "levels/dc/dc_treasure_green_break/geo.inc.c"
#include "levels/dc/dc_treasure_red_break/geo.inc.c"
#include "levels/dc/dc_sandglass_ends/geo.inc.c"
#include "levels/dc/dc_sandglass_glass/geo.inc.c"
#include "levels/dc/dc_sandglass_sand/geo.inc.c"
#include "levels/dc/dc_sandglass_sandf/geo.inc.c"
#include "levels/dc/dc_sandglass_spring/geo.inc.c"