#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "textures.h"
#include "dialog_ids.h"
#include "spring_desc.h"

#include "make_const_nonconst.h"

#if 0
#include "levels/dc/leveldata.inc.c"
#else
#include "levels/dc/header.h"
#include "levels/dc/area_1/macro.inc.c"
#include "levels/dc/area_1/spline.inc.c"
#include "levels/dc/visual/model_lvlopt.inc.c"
#include "levels/dc/flipbook.inc.c"
#include "levels/dc/rails.inc.c"
#endif

#include "levels/dc/dc_door_b/collision.inc.c"
#include "levels/dc/dc_door_b/model.inc.c"
#include "levels/dc/dc_door_g/model.inc.c"
#include "levels/dc/dc_door_n/model.inc.c"
#include "levels/dc/dc_door_r/model.inc.c"
#include "levels/dc/dc_box_blue/model.inc.c"
#include "levels/dc/dc_box_blue_break/model.inc.c"
#include "levels/dc/dc_box_green/model.inc.c"
#include "levels/dc/dc_box_red/model.inc.c"
#include "levels/dc/dc_box_green_break/model.inc.c"
#include "levels/dc/dc_box_red_break/model.inc.c"
#include "levels/dc/dc_treasure_blue/model.inc.c"
#include "levels/dc/dc_treasure_green/model.inc.c"
#include "levels/dc/dc_treasure_red/model.inc.c"
#include "levels/dc/dc_treasure_blue_break/model.inc.c"
#include "levels/dc/dc_treasure_green_break/model.inc.c"
#include "levels/dc/dc_treasure_red_break/model.inc.c"
#include "levels/dc/dc_sandglass_ends/model.inc.c"
#include "levels/dc/dc_sandglass_glass/model.inc.c"
#include "levels/dc/dc_sandglass_sand/model.inc.c"
#include "levels/dc/dc_sandglass_sandf/model.inc.c"
#include "levels/dc/dc_sandglass_spring/model.inc.c"