#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/dc/leveldata.inc.c"
#include "levels/dc/dc_door_b/collision.inc.c"
#include "levels/dc/dc_door_b/model.inc.c"
#include "levels/dc/dc_door_g/model.inc.c"
#include "levels/dc/dc_door_n/model.inc.c"
#include "levels/dc/dc_door_r/model.inc.c"
#include "levels/dc/dc_box_blue/model.inc.c"
#include "levels/dc/dc_box_blue_break/model.inc.c"
#include "levels/dc/dc_box_green/model.inc.c"
#include "levels/dc/dc_box_red/model.inc.c"
#include "levels/dc/dc_box_green_break/model.inc.c"
#include "levels/dc/dc_box_red_break/model.inc.c"
#include "levels/dc/dc_treasure_blue/model.inc.c"
#include "levels/dc/dc_treasure_green/model.inc.c"
#include "levels/dc/dc_treasure_red/model.inc.c"
#include "levels/dc/dc_treasure_blue_break/model.inc.c"
#include "levels/dc/dc_treasure_green_break/model.inc.c"
#include "levels/dc/dc_treasure_red_break/model.inc.c"