extern const GeoLayout ce_area_1_geo[];
extern const GeoLayout ce_area_1[];
extern const Collision ce_area_1_collision[];
extern const MacroObject ce_area_1_macro_objs[];
extern const GeoLayout ce_area_10_geo[];
extern const GeoLayout ce_area_10[];
extern const Collision ce_area_10_collision[];
extern const MacroObject ce_area_10_macro_objs[];
extern const GeoLayout ce_area_2_geo[];
extern const GeoLayout ce_area_2[];
extern const Collision ce_area_2_collision[];
extern const MacroObject ce_area_2_macro_objs[];
extern const GeoLayout ce_area_3_geo[];
extern const GeoLayout ce_area_3[];
extern const Collision ce_area_3_collision[];
extern const MacroObject ce_area_3_macro_objs[];
extern const Trajectory ce_area_3_spline_2459_object_00CFC480_001[];
extern const Trajectory ce_area_3_spline_2473_object_00CFEC08_001[];
extern const Trajectory ce_area_3_spline_z_1681_object_00D2405C_001[];
extern const Trajectory ce_area_3_spline_z_1757_object_00CA7120_001[];
extern const Trajectory ce_area_3_spline_z_1757_object_00CA7120_002[];
extern const GeoLayout ce_area_4_geo[];
extern const GeoLayout ce_area_4[];
extern const Collision ce_area_4_collision[];
extern const MacroObject ce_area_4_macro_objs[];
extern const GeoLayout ce_area_5_geo[];
extern const GeoLayout ce_area_5[];
extern const Collision ce_area_5_collision[];
extern const MacroObject ce_area_5_macro_objs[];
extern const Trajectory ce_area_5_spline_2561_object_00D05490_001[];
extern const GeoLayout ce_area_6_geo[];
extern const GeoLayout ce_area_6[];
extern const Collision ce_area_6_collision[];
extern const MacroObject ce_area_6_macro_objs[];
extern const Trajectory ce_area_6_spline_0870_object_00D2DB3C_001[];
extern const Trajectory ce_area_6_spline_2443_object_00D39804_002[];
extern const Trajectory ce_area_6_spline_2480_object_00D39A6C_001[];
extern const GeoLayout ce_area_7_geo[];
extern const GeoLayout ce_area_7[];
extern const Collision ce_area_7_collision[];
extern const MacroObject ce_area_7_macro_objs[];
extern const Trajectory ce_area_7_spline_2443_object_00D39804_001[];
extern const Trajectory ce_area_7_spline_2449_object_00CFAC10_001[];
extern const Trajectory ce_area_7_spline_2479_object_00D39A34_001[];
extern const GeoLayout ce_area_8_geo[];
extern const GeoLayout ce_area_8[];
extern const Collision ce_area_8_collision[];
extern const MacroObject ce_area_8_macro_objs[];
extern const GeoLayout ce_area_9_geo[];
extern const GeoLayout ce_area_9[];
extern const Collision ce_area_9_collision[];
extern const MacroObject ce_area_9_macro_objs[];
extern Vtx ce_dl_a1_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a1_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a10_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a10_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a2_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a2_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a3_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a3_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a4_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a4_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a5_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a5_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a6_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a6_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a7_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a7_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a8_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a8_mesh_layer_1_tri_0[];
extern Vtx ce_dl_a9_mesh_layer_1_vtx_0[24];
extern Gfx ce_dl_a9_mesh_layer_1_tri_0[];
extern Gfx mat_ce_dl_f3dlite_material[];
extern Gfx mat_revert_ce_dl_f3dlite_material[];
extern Gfx mat_ce_dl_f3dlite_material_009[];
extern Gfx mat_revert_ce_dl_f3dlite_material_009[];
extern Gfx mat_ce_dl_f3dlite_material_001[];
extern Gfx mat_revert_ce_dl_f3dlite_material_001[];
extern Gfx mat_ce_dl_f3dlite_material_002[];
extern Gfx mat_revert_ce_dl_f3dlite_material_002[];
extern Gfx mat_ce_dl_f3dlite_material_003[];
extern Gfx mat_revert_ce_dl_f3dlite_material_003[];
extern Gfx mat_ce_dl_f3dlite_material_004[];
extern Gfx mat_revert_ce_dl_f3dlite_material_004[];
extern Gfx mat_ce_dl_f3dlite_material_005[];
extern Gfx mat_revert_ce_dl_f3dlite_material_005[];
extern Gfx mat_ce_dl_f3dlite_material_006[];
extern Gfx mat_revert_ce_dl_f3dlite_material_006[];
extern Gfx mat_ce_dl_f3dlite_material_007[];
extern Gfx mat_revert_ce_dl_f3dlite_material_007[];
extern Gfx mat_ce_dl_f3dlite_material_008[];
extern Gfx mat_revert_ce_dl_f3dlite_material_008[];
extern Gfx ce_dl_a1_mesh_layer_1[];
extern Gfx ce_dl_a10_mesh_layer_1[];
extern Gfx ce_dl_a2_mesh_layer_1[];
extern Gfx ce_dl_a3_mesh_layer_1[];
extern Gfx ce_dl_a4_mesh_layer_1[];
extern Gfx ce_dl_a5_mesh_layer_1[];
extern Gfx ce_dl_a6_mesh_layer_1[];
extern Gfx ce_dl_a7_mesh_layer_1[];
extern Gfx ce_dl_a8_mesh_layer_1[];
extern Gfx ce_dl_a9_mesh_layer_1[];
