extern const GeoLayout sr_area_1_geo[];
extern const GeoLayout sr_area_1[];
extern const Collision sr_area_1_collision[];
extern const MacroObject sr_area_1_macro_objs[];
extern const GeoLayout sr_area_2_geo[];
extern const GeoLayout sr_area_2[];
extern const Collision sr_area_2_collision[];
extern const MacroObject sr_area_2_macro_objs[];
extern const GeoLayout sr_area_3_geo[];
extern const GeoLayout sr_area_3[];
extern const Collision sr_area_3_collision[];
extern const MacroObject sr_area_3_macro_objs[];
extern Vtx sr_dl_a3_001_mesh_layer_5_vtx_0[24];
extern Gfx sr_dl_a3_001_mesh_layer_5_tri_0[];
extern Vtx sr_dl_a3_002_mesh_layer_5_vtx_0[24];
extern Gfx sr_dl_a3_002_mesh_layer_5_tri_0[];
extern Vtx sr_dl_a3_003_mesh_layer_5_vtx_0[24];
extern Gfx sr_dl_a3_003_mesh_layer_5_tri_0[];
extern Gfx mat_sr_dl_f3dlite_material_002[];
extern Gfx mat_revert_sr_dl_f3dlite_material_002[];
extern Gfx sr_dl_a3_001_mesh_layer_5[];
extern Gfx sr_dl_a3_002_mesh_layer_5[];
extern Gfx sr_dl_a3_003_mesh_layer_5[];
