extern const GeoLayout wc_box_break_geo[];
extern u8 wc_box_break_dz_takarabako128_001_ci4[];
extern u8 wc_box_break_dz_takarabako128_001_pal_rgba16[];
extern u8 wc_box_break_dz_wc_shadow_sq32_001_rgba16[];
extern Vtx wc_box_break_wc_box_break_mesh_layer_1_vtx_cull[8];
extern Vtx wc_box_break_wc_box_break_mesh_layer_1_vtx_0[65];
extern Vtx wc_box_break_wc_box_break_mesh_layer_6_vtx_cull[8];
extern Vtx wc_box_break_wc_box_break_mesh_layer_6_vtx_0[10];
extern Gfx wc_box_break_wc_box_break_mesh_layer_1[];
extern Gfx wc_box_break_wc_box_break_mesh_layer_6[];
