extern const GeoLayout ee_area_1_geo[];
extern const GeoLayout ee_area_1[];
extern const Collision ee_area_1_collision[];
extern const MacroObject ee_area_1_macro_objs[];
extern const GeoLayout ee_area_2_geo[];
extern const GeoLayout ee_area_2[];
extern const Collision ee_area_2_collision[];
extern const MacroObject ee_area_2_macro_objs[];
extern const GeoLayout ee_area_3_geo[];
extern const GeoLayout ee_area_3[];
extern const Collision ee_area_3_collision[];
extern const MacroObject ee_area_3_macro_objs[];
extern const GeoLayout ee_area_4_geo[];
extern const GeoLayout ee_area_4[];
extern const Collision ee_area_4_collision[];
extern const MacroObject ee_area_4_macro_objs[];
extern const GeoLayout ee_area_5_geo[];
extern const GeoLayout ee_area_5[];
extern const Collision ee_area_5_collision[];
extern const MacroObject ee_area_5_macro_objs[];
extern u8 ee_dl_et128_1_001_ci4[];
extern u8 ee_dl_et128_1_001_pal_rgba16[];
extern Vtx ee_dl_a1_002_mesh_layer_1_vtx_0[24];
extern Gfx ee_dl_a1_002_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_004_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_005_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_005_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_005_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_006_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_006_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_006_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_007_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_007_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_007_mesh_layer_1_tri_0[];
extern Vtx ee_dl_a1_001_mesh_layer_1_vtx_0[24];
extern Gfx ee_dl_a1_001_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_008_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_008_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_008_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_009_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_009_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_009_mesh_layer_1_tri_0[];
extern Vtx ee_dl_a1_003_mesh_layer_1_vtx_0[24];
extern Gfx ee_dl_a1_003_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_010_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_010_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_010_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_011_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_011_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_011_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_012_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_012_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_012_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_013_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_013_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_013_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_014_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_014_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_014_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_015_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_015_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_015_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_016_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_016_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_016_mesh_layer_1_tri_0[];
extern Vtx ee_dl_a1_004_mesh_layer_1_vtx_0[24];
extern Gfx ee_dl_a1_004_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_017_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_017_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_017_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_018_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_018_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_018_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_019_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_019_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_019_mesh_layer_1_tri_0[];
extern Vtx ee_dl_a1_005_mesh_layer_1_vtx_0[24];
extern Gfx ee_dl_a1_005_mesh_layer_1_tri_0[];
extern Vtx ee_dl_object_0058E1E0_mesh_layer_1_vtx_0[96];
extern Gfx ee_dl_object_0058E1E0_mesh_layer_1_tri_0[];
extern Vtx ee_dl_object_0058F7E0_mesh_layer_1_vtx_0[40];
extern Gfx ee_dl_object_0058F7E0_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_020_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_020_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_020_mesh_layer_1_tri_0[];
extern Vtx ee_dl_Plane_021_mesh_layer_1_vtx_cull[8];
extern Vtx ee_dl_Plane_021_mesh_layer_1_vtx_0[4];
extern Gfx ee_dl_Plane_021_mesh_layer_1_tri_0[];
extern Gfx mat_ee_dl_f3dlite_material[];
extern Gfx mat_revert_ee_dl_f3dlite_material[];
extern Gfx mat_ee_dl_f3dlite_material_002[];
extern Gfx mat_revert_ee_dl_f3dlite_material_002[];
extern Gfx mat_ee_dl_f3dlite_material_003[];
extern Gfx mat_revert_ee_dl_f3dlite_material_003[];
extern Gfx mat_ee_dl_f3dlite_material_004[];
extern Gfx mat_revert_ee_dl_f3dlite_material_004[];
extern Gfx mat_ee_dl_f3dlite_material_005[];
extern Gfx mat_revert_ee_dl_f3dlite_material_005[];
extern Gfx mat_ee_dl_f3dlite_material_006[];
extern Gfx mat_revert_ee_dl_f3dlite_material_006[];
extern Gfx mat_ee_dl_f3dlite_material_007[];
extern Gfx mat_revert_ee_dl_f3dlite_material_007[];
extern Gfx mat_ee_dl_f3dlite_material_008[];
extern Gfx mat_revert_ee_dl_f3dlite_material_008[];
extern Gfx mat_ee_dl_f3dlite_material_009[];
extern Gfx mat_revert_ee_dl_f3dlite_material_009[];
extern Gfx mat_ee_dl_f3dlite_material_010[];
extern Gfx mat_revert_ee_dl_f3dlite_material_010[];
extern Gfx mat_ee_dl_f3dlite_material_011[];
extern Gfx mat_revert_ee_dl_f3dlite_material_011[];
extern Gfx mat_ee_dl_f3dlite_material_012[];
extern Gfx mat_revert_ee_dl_f3dlite_material_012[];
extern Gfx mat_ee_dl_f3dlite_material_013[];
extern Gfx mat_revert_ee_dl_f3dlite_material_013[];
extern Gfx mat_ee_dl_f3dlite_material_014[];
extern Gfx mat_revert_ee_dl_f3dlite_material_014[];
extern Gfx mat_ee_dl_f3dlite_material_015[];
extern Gfx mat_revert_ee_dl_f3dlite_material_015[];
extern Gfx mat_ee_dl_f3dlite_material_016[];
extern Gfx mat_revert_ee_dl_f3dlite_material_016[];
extern Gfx mat_ee_dl_f3dlite_material_017[];
extern Gfx mat_revert_ee_dl_f3dlite_material_017[];
extern Gfx mat_ee_dl_f3dlite_material_018[];
extern Gfx mat_revert_ee_dl_f3dlite_material_018[];
extern Gfx mat_ee_dl_f3dlite_material_019[];
extern Gfx mat_revert_ee_dl_f3dlite_material_019[];
extern Gfx mat_ee_dl_f3dlite_material_020[];
extern Gfx mat_revert_ee_dl_f3dlite_material_020[];
extern Gfx mat_ee_dl_PowerSupply_sa1mdl_0_f3d[];
extern Gfx mat_revert_ee_dl_PowerSupply_sa1mdl_0_f3d[];
extern Gfx mat_ee_dl_PowerSupplyShield_sa1mdl_0_f3d[];
extern Gfx mat_revert_ee_dl_PowerSupplyShield_sa1mdl_0_f3d[];
extern Gfx mat_ee_dl_f3dlite_material_021[];
extern Gfx mat_revert_ee_dl_f3dlite_material_021[];
extern Gfx mat_ee_dl_f3dlite_material_022[];
extern Gfx mat_revert_ee_dl_f3dlite_material_022[];
extern Gfx ee_dl_a1_002_mesh_layer_1[];
extern Gfx ee_dl_Plane_001_mesh_layer_1[];
extern Gfx ee_dl_Plane_002_mesh_layer_1[];
extern Gfx ee_dl_Plane_003_mesh_layer_1[];
extern Gfx ee_dl_Plane_004_mesh_layer_1[];
extern Gfx ee_dl_Plane_005_mesh_layer_1[];
extern Gfx ee_dl_Plane_006_mesh_layer_1[];
extern Gfx ee_dl_Plane_007_mesh_layer_1[];
extern Gfx ee_dl_a1_001_mesh_layer_1[];
extern Gfx ee_dl_Plane_008_mesh_layer_1[];
extern Gfx ee_dl_Plane_009_mesh_layer_1[];
extern Gfx ee_dl_a1_003_mesh_layer_1[];
extern Gfx ee_dl_Plane_010_mesh_layer_1[];
extern Gfx ee_dl_Plane_011_mesh_layer_1[];
extern Gfx ee_dl_Plane_012_mesh_layer_1[];
extern Gfx ee_dl_Plane_013_mesh_layer_1[];
extern Gfx ee_dl_Plane_014_mesh_layer_1[];
extern Gfx ee_dl_Plane_015_mesh_layer_1[];
extern Gfx ee_dl_Plane_016_mesh_layer_1[];
extern Gfx ee_dl_a1_004_mesh_layer_1[];
extern Gfx ee_dl_Plane_017_mesh_layer_1[];
extern Gfx ee_dl_Plane_018_mesh_layer_1[];
extern Gfx ee_dl_Plane_019_mesh_layer_1[];
extern Gfx ee_dl_a1_005_mesh_layer_1[];
extern Gfx ee_dl_object_0058E1E0_mesh_layer_1[];
extern Gfx ee_dl_object_0058F7E0_mesh_layer_1[];
extern Gfx ee_dl_Plane_020_mesh_layer_1[];
extern Gfx ee_dl_Plane_021_mesh_layer_1[];
