extern const GeoLayout ph_terminal_geo[];
extern u8 ph_terminal_pum32_1_ci8[];
extern u8 ph_terminal_pum32_1_pal_rgba16[];
extern u8 ph_terminal_pum64_4_ci4[];
extern u8 ph_terminal_pum64_4_pal_rgba16[];
extern Vtx ph_terminal_ph_terminal_mesh_layer_1_vtx_0[24];
extern Gfx ph_terminal_ph_terminal_mesh_layer_1_tri_0[];
extern Vtx ph_terminal_ph_terminal_mesh_layer_1_vtx_1[12];
extern Gfx ph_terminal_ph_terminal_mesh_layer_1_tri_1[];
extern Vtx ph_terminal_ph_terminal_mesh_layer_1_vtx_2[24];
extern Gfx ph_terminal_ph_terminal_mesh_layer_1_tri_2[];
extern Gfx mat_ph_terminal_TERMINAL_sa2bmdl_0_f3d[];
extern Gfx mat_revert_ph_terminal_TERMINAL_sa2bmdl_0_f3d[];
extern Gfx mat_ph_terminal_TERMINAL_sa2bmdl_1_f3d[];
extern Gfx mat_revert_ph_terminal_TERMINAL_sa2bmdl_1_f3d[];
extern Gfx mat_ph_terminal_TERMINAL_sa2bmdl_2_f3d[];
extern Gfx mat_revert_ph_terminal_TERMINAL_sa2bmdl_2_f3d[];
extern Gfx ph_terminal_ph_terminal_mesh_layer_1[];
