extern const GeoLayout pc_area_1_geo[];
extern const GeoLayout pc_area_1[];
extern const Collision pc_area_1_collision[];
extern const MacroObject pc_area_1_macro_objs[];
extern const GeoLayout pc_area_2_geo[];
extern const GeoLayout pc_area_2[];
extern const Collision pc_area_2_collision[];
extern const MacroObject pc_area_2_macro_objs[];
extern const Trajectory pc_area_2_spline_NurbsCurve_Spring[];
extern const Trajectory pc_area_2_spline_NurbsCurve_Spring_001[];
extern const GeoLayout pc_area_3_geo[];
extern const GeoLayout pc_area_3[];
extern const Collision pc_area_3_collision[];
extern const MacroObject pc_area_3_macro_objs[];
extern const Trajectory pc_area_3_spline_NurbsCurve_Loop[];
extern const Trajectory pc_area_3_spline_NurbsCurve_Spring_002[];
extern const GeoLayout pc_area_4_geo[];
extern const GeoLayout pc_area_4[];
extern const Collision pc_area_4_collision[];
extern const MacroObject pc_area_4_macro_objs[];
extern const Trajectory pc_area_4_spline_NurbsCurve_Rail[];
extern const Trajectory pc_area_4_spline_NurbsCurve_Spring_003[];
extern const GeoLayout pc_area_5_geo[];
extern const GeoLayout pc_area_5[];
extern const Collision pc_area_5_collision[];
extern const MacroObject pc_area_5_macro_objs[];
extern const Trajectory pc_area_5_spline_NurbsCurve_Rail_001[];
extern const Trajectory pc_area_5_spline_NurbsCurve_Rail_002[];
extern const GeoLayout pc_area_6_geo[];
extern const GeoLayout pc_area_6[];
extern const Collision pc_area_6_collision[];
extern const MacroObject pc_area_6_macro_objs[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Rail_003[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Rail_004[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Rail_005[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Rail_006[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Rail_007[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Spring_004[];
extern const Trajectory pc_area_6_spline_NurbsCurve_Spring_010[];
extern const GeoLayout pc_area_7_geo[];
extern const GeoLayout pc_area_7[];
extern const Collision pc_area_7_collision[];
extern const MacroObject pc_area_7_macro_objs[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Loop_001[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Loop_002[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Rail_008[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Spring_005[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Spring_006[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Spring_008[];
extern const Trajectory pc_area_7_spline_NurbsCurve_Spring_011[];
extern const GeoLayout pc_area_8_geo[];
extern const GeoLayout pc_area_8[];
extern const Collision pc_area_8_collision[];
extern const MacroObject pc_area_8_macro_objs[];
extern const Trajectory pc_area_8_spline_NurbsCurve_Loop_003[];
extern const Trajectory pc_area_8_spline_NurbsCurve_Loop_004[];
extern const Trajectory pc_area_8_spline_NurbsCurve_Rail_009[];
extern const Trajectory pc_area_8_spline_NurbsCurve_Spring_007[];
extern const Trajectory pc_area_8_spline_NurbsCurve_Spring_009[];
extern u8 pc_dl_kd_pc_ami1_ci8[];
extern u8 pc_dl_kd_pc_ami1_pal_rgba16[];
extern u8 pc_dl_dz_pc_ironbar_dish128_ci4[];
extern u8 pc_dl_dz_pc_ironbar_dish128_pal_rgba16[];
extern u8 pc_dl_kd_pc_hasira5_ci4[];
extern u8 pc_dl_kd_pc_hasira5_pal_rgba16[];
extern Vtx pc_dl_0383_object_0114A508_mesh_layer_1_vtx_0[20];
extern Gfx pc_dl_0383_object_0114A508_mesh_layer_1_tri_0[];
extern Vtx pc_dl_a1_mesh_layer_1_vtx_0[24];
extern Gfx pc_dl_a1_mesh_layer_1_tri_0[];
extern Vtx pc_dl_C_pc_block_mesh_layer_1_vtx_0[8];
extern Gfx pc_dl_C_pc_block_mesh_layer_1_tri_0[];
extern Vtx pc_dl_object_006A0C08_mesh_layer_1_vtx_0[20];
extern Gfx pc_dl_object_006A0C08_mesh_layer_1_tri_0[];
extern Vtx pc_dl_object_006B5B48_mesh_layer_1_vtx_0[86];
extern Gfx pc_dl_object_006B5B48_mesh_layer_1_tri_0[];
extern Vtx pc_dl_C_pc_keyhole_mesh_layer_1_vtx_0[17];
extern Gfx pc_dl_C_pc_keyhole_mesh_layer_1_tri_0[];
extern Vtx pc_dl_object_0069FFB8_mesh_layer_1_vtx_0[20];
extern Gfx pc_dl_object_0069FFB8_mesh_layer_1_tri_0[];
extern Vtx pc_dl_object_006BF7DC_004_mesh_layer_1_vtx_0[32];
extern Gfx pc_dl_object_006BF7DC_004_mesh_layer_1_tri_0[];
extern Vtx pc_dl_object_006C9200_mesh_layer_1_vtx_0[18];
extern Gfx pc_dl_object_006C9200_mesh_layer_1_tri_0[];
extern Vtx pc_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx pc_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_pc_dl_objLandTable0028_sa2blvl_58_f3d[];
extern Gfx mat_revert_pc_dl_objLandTable0028_sa2blvl_58_f3d[];
extern Gfx mat_pc_dl_f3dlite_material[];
extern Gfx mat_revert_pc_dl_f3dlite_material[];
extern Gfx mat_pc_dl_BLOCK_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_BLOCK_sa1mdl_0_f3d[];
extern Gfx mat_pc_dl_SNAKESTATUE_LEFT_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_SNAKESTATUE_LEFT_sa1mdl_0_f3d[];
extern Gfx mat_pc_dl_FIREPOT_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_FIREPOT_sa1mdl_0_f3d[];
extern Gfx mat_pc_dl_KEYHOLE_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_KEYHOLE_sa1mdl_0_f3d[];
extern Gfx mat_pc_dl_SNAKESTATUE_RIGHT_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_SNAKESTATUE_RIGHT_sa1mdl_0_f3d[];
// extern Gfx mat_pc_dl_TORCHCUP_sa2mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_TORCHCUP_sa2mdl_0_f3d[];
extern Gfx mat_pc_dl_SNEAKRAIL_sa1mdl_0_f3d[];
extern Gfx mat_revert_pc_dl_SNEAKRAIL_sa1mdl_0_f3d[];
extern Gfx mat_pc_dl_f3dlite_material_021[];
extern Gfx mat_revert_pc_dl_f3dlite_material_021[];
extern Gfx pc_dl_0383_object_0114A508_mesh_layer_1[];
extern Gfx pc_dl_a1_mesh_layer_1[];
extern Gfx pc_dl_C_pc_block_mesh_layer_1[];
extern Gfx pc_dl_object_006A0C08_mesh_layer_1[];
extern Gfx pc_dl_object_006B5B48_mesh_layer_1[];
extern Gfx pc_dl_C_pc_keyhole_mesh_layer_1[];
extern Gfx pc_dl_object_0069FFB8_mesh_layer_1[];
extern Gfx pc_dl_object_006BF7DC_004_mesh_layer_1[];
extern Gfx pc_dl_object_006C9200_mesh_layer_1[];
extern Gfx pc_dl_Plane_001_mesh_layer_1[];
