extern const GeoLayout pc_area_1_geo[];
extern const GeoLayout pc_area_1[];
extern const Collision pc_area_1_collision[];
extern const MacroObject pc_area_1_macro_objs[];
extern const GeoLayout pc_area_2_geo[];
extern const GeoLayout pc_area_2[];
extern const Collision pc_area_2_collision[];
extern const MacroObject pc_area_2_macro_objs[];
extern const GeoLayout pc_area_3_geo[];
extern const GeoLayout pc_area_3[];
extern const Collision pc_area_3_collision[];
extern const MacroObject pc_area_3_macro_objs[];
extern const GeoLayout pc_area_4_geo[];
extern const GeoLayout pc_area_4[];
extern const Collision pc_area_4_collision[];
extern const MacroObject pc_area_4_macro_objs[];
extern const GeoLayout pc_area_5_geo[];
extern const GeoLayout pc_area_5[];
extern const Collision pc_area_5_collision[];
extern const MacroObject pc_area_5_macro_objs[];
extern const GeoLayout pc_area_6_geo[];
extern const GeoLayout pc_area_6[];
extern const Collision pc_area_6_collision[];
extern const MacroObject pc_area_6_macro_objs[];
extern const GeoLayout pc_area_7_geo[];
extern const GeoLayout pc_area_7[];
extern const Collision pc_area_7_collision[];
extern const MacroObject pc_area_7_macro_objs[];
extern const GeoLayout pc_area_8_geo[];
extern const GeoLayout pc_area_8[];
extern const Collision pc_area_8_collision[];
extern const MacroObject pc_area_8_macro_objs[];
extern Vtx pc_dl_a1_mesh_layer_1_vtx_0[24];
extern Gfx pc_dl_a1_mesh_layer_1_tri_0[];
extern Gfx mat_pc_dl_f3dlite_material[];
extern Gfx mat_revert_pc_dl_f3dlite_material[];
extern Gfx pc_dl_a1_mesh_layer_1[];
