extern const GeoLayout wj_area_1_geo[];
extern const GeoLayout wj_area_1[];
extern const Collision wj_area_1_collision[];
extern const MacroObject wj_area_1_macro_objs[];
extern const GeoLayout wj_area_2_geo[];
extern const GeoLayout wj_area_2[];
extern const Collision wj_area_2_collision[];
extern const MacroObject wj_area_2_macro_objs[];
extern const GeoLayout wj_area_3_geo[];
extern const GeoLayout wj_area_3[];
extern const Collision wj_area_3_collision[];
extern const MacroObject wj_area_3_macro_objs[];
extern const GeoLayout wj_area_4_geo[];
extern const GeoLayout wj_area_4[];
extern const Collision wj_area_4_collision[];
extern const MacroObject wj_area_4_macro_objs[];
extern const GeoLayout wj_area_5_geo[];
extern const GeoLayout wj_area_5[];
extern const Collision wj_area_5_collision[];
extern const MacroObject wj_area_5_macro_objs[];
extern u8 wj_dl_jungle128_9_001_ci4[];
extern u8 wj_dl_jungle128_9_001_pal_rgba16[];
extern u8 wj_dl_jungle64_1_001_ia16[];
extern Vtx wj_dl_a3_001_mesh_layer_5_vtx_0[24];
extern Vtx wj_dl_C_object_00C726A0_mesh_layer_1_vtx_0[8];
extern Vtx wj_dl_V_object_00C72CD0_mesh_layer_1_vtx_0[18];
extern Vtx wj_dl_V_object_00C72CD0_mesh_layer_1_vtx_1[32];
extern Vtx wj_dl_V_object_00C72CD0_mesh_layer_5_vtx_0[8];
extern Vtx wj_dl_a3_002_mesh_layer_5_vtx_0[24];
extern Vtx wj_dl_a3_003_mesh_layer_5_vtx_0[24];
extern Vtx wj_dl_a3_004_mesh_layer_5_vtx_0[24];
extern Vtx wj_dl_a3_005_mesh_layer_5_vtx_0[24];
extern Gfx wj_dl_a3_001_mesh_layer_5[];
extern Gfx wj_dl_C_object_00C726A0_mesh_layer_1[];
extern Gfx wj_dl_V_object_00C72CD0_mesh_layer_1[];
extern Gfx wj_dl_V_object_00C72CD0_mesh_layer_5[];
extern Gfx wj_dl_a3_002_mesh_layer_5[];
extern Gfx wj_dl_a3_003_mesh_layer_5[];
extern Gfx wj_dl_a3_004_mesh_layer_5[];
extern Gfx wj_dl_a3_005_mesh_layer_5[];
