extern const GeoLayout ms_area_1_geo[];
extern const GeoLayout ms_area_1[];
extern const Collision ms_area_1_collision[];
extern const MacroObject ms_area_1_macro_objs[];
extern const GeoLayout ms_area_2_geo[];
extern const GeoLayout ms_area_2[];
extern const Collision ms_area_2_collision[];
extern const MacroObject ms_area_2_macro_objs[];
extern const GeoLayout ms_area_3_geo[];
extern const GeoLayout ms_area_3[];
extern const Collision ms_area_3_collision[];
extern const MacroObject ms_area_3_macro_objs[];
extern Vtx ms_dl_a1_mesh_layer_1_vtx_0[24];
extern Gfx ms_dl_a1_mesh_layer_1_tri_0[];
extern Vtx ms_dl_a1_005_mesh_layer_1_vtx_0[4];
extern Gfx ms_dl_a1_005_mesh_layer_1_tri_0[];
extern Vtx ms_dl_a1_001_mesh_layer_1_vtx_0[24];
extern Gfx ms_dl_a1_001_mesh_layer_1_tri_0[];
extern Vtx ms_dl_a1_004_mesh_layer_1_vtx_0[4];
extern Gfx ms_dl_a1_004_mesh_layer_1_tri_0[];
extern Vtx ms_dl_a1_002_mesh_layer_1_vtx_0[24];
extern Gfx ms_dl_a1_002_mesh_layer_1_tri_0[];
extern Gfx mat_ms_dl_f3dlite_material[];
extern Gfx mat_revert_ms_dl_f3dlite_material[];
extern Gfx ms_dl_a1_mesh_layer_1[];
extern Gfx ms_dl_a1_005_mesh_layer_1[];
extern Gfx ms_dl_a1_001_mesh_layer_1[];
extern Gfx ms_dl_a1_004_mesh_layer_1[];
extern Gfx ms_dl_a1_002_mesh_layer_1[];
