extern const GeoLayout wc_stonehead_path_geo[];
extern u8 wc_stonehead_path_dz_wc_stonehead_railedga64_001_ci4[];
extern u8 wc_stonehead_path_dz_wc_stonehead_railedga64_001_pal_rgba16[];
extern u8 wc_stonehead_path_dz_wc_stonehead_rail64_001_ci4[];
extern u8 wc_stonehead_path_dz_wc_stonehead_rail64_001_pal_rgba16[];
extern Vtx wc_stonehead_path_wc_stonehead_path_mesh_layer_4_vtx_cull[8];
extern Vtx wc_stonehead_path_wc_stonehead_path_mesh_layer_4_vtx_0[8];
extern Vtx wc_stonehead_path_wc_stonehead_path_mesh_layer_4_vtx_1[4];
extern Gfx wc_stonehead_path_wc_stonehead_path_mesh_layer_4[];
