#include "src/game/envfx_snow.h"

extern Gfx *geo_update_alpha_compare_credits(s32 callContext, struct GraphNode *node, UNUSED void *context);
const GeoLayout castle_courtyard_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_TRANSPARENT, geo_update_alpha_compare_credits),
		GEO_ASM(LAYER_PCL, geo_update_alpha_compare_credits),
		GEO_ASM(LAYER_ALPHA, geo_update_alpha_compare_credits),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Shape_IndexedFaceSet_009_Shape_IndexedFaceSet_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Shape_IndexedFaceSet_009_Shape_IndexedFaceSet_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_PCL, castle_courtyard_dl_Shape_IndexedFaceSet_009_Shape_IndexedFaceSet_131_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_courtyard_dl_Shape_IndexedFaceSet_009_Shape_IndexedFaceSet_131_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_courtyard_dl_Shape_IndexedFaceSet_009_Shape_IndexedFaceSet_131_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_courtyard_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1000, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_courtyard_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
