extern const GeoLayout wc_fan_bright_geo[];
extern u8 wc_fan_bright_dz_hata_longhook32a_001_rgba16[];
extern u8 wc_fan_bright_kd_nde_hasira9_vq_001_ci4[];
extern u8 wc_fan_bright_kd_nde_hasira9_vq_001_pal_rgba16[];
extern u8 wc_fan_bright_dz_wc_eyepro_alpha_128_001_ci4[];
extern u8 wc_fan_bright_dz_wc_eyepro_alpha_128_001_pal_rgba16[];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_5_vtx_cull[8];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_5_vtx_0[24];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_1_vtx_cull[8];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_1_vtx_0[171];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_4_vtx_cull[8];
extern Vtx wc_fan_bright_wc_fan_bright_mesh_layer_4_vtx_0[32];
extern Gfx wc_fan_bright_wc_fan_bright_mesh_layer_5[];
extern Gfx wc_fan_bright_wc_fan_bright_mesh_layer_1[];
extern Gfx wc_fan_bright_wc_fan_bright_mesh_layer_4[];
