#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/mhe/leveldata.inc.c"
#include "levels/mhe/mhe_skybox/model.inc.c"
#include "levels/mhe/mhe_bigshutter/model.inc.c"
#include "levels/mhe/mhe_bigshutter/collision.inc.c"
#include "levels/mhe/mhe_fireball/model.inc.c"
#include "levels/mhe/mhe_fireball_break/model.inc.c"
#include "levels/mhe/mhe_meteo_a/model.inc.c"
#include "levels/mhe/mhe_meteo_b/model.inc.c"
#include "levels/mhe/mhe_meteo_break_a/model.inc.c"
#include "levels/mhe/mhe_meteobig/model.inc.c"
#include "levels/mhe/mhe_meteobig_break/model.inc.c"
#include "levels/mhe/mhe_meteo_fall/model.inc.c"
#include "levels/mhe/mhe_meteoshut/model.inc.c"
#include "levels/mhe/mhe_meteoshut/collision.inc.c"
#include "levels/mhe/mhe_tank/model.inc.c"
#include "levels/mhe/mhe_tank_break/model.inc.c"