extern const GeoLayout pl_tank_breaka_geo[];
extern u8 pl_tank_breaka_pr128_14_ci4[];
extern u8 pl_tank_breaka_pr128_14_pal_rgba16[];
extern u8 pl_tank_breaka_miu128_ig009_ci4[];
extern u8 pl_tank_breaka_miu128_ig009_pal_rgba16[];
extern Vtx pl_tank_breaka_pl_tank_breaka_mesh_layer_1_vtx_cull[8];
extern Vtx pl_tank_breaka_pl_tank_breaka_mesh_layer_1_vtx_0[4];
extern Gfx pl_tank_breaka_pl_tank_breaka_mesh_layer_1_tri_0[];
extern Vtx pl_tank_breaka_pl_tank_breaka_mesh_layer_1_vtx_1[16];
extern Gfx pl_tank_breaka_pl_tank_breaka_mesh_layer_1_tri_1[];
extern Gfx mat_pl_tank_breaka_TANK_BREAKA_sa2mdl_0_f3d[];
extern Gfx mat_revert_pl_tank_breaka_TANK_BREAKA_sa2mdl_0_f3d[];
extern Gfx mat_pl_tank_breaka_TANK_BREAKA_sa2mdl_1_f3d[];
extern Gfx mat_revert_pl_tank_breaka_TANK_BREAKA_sa2mdl_1_f3d[];
extern Gfx pl_tank_breaka_pl_tank_breaka_mesh_layer_1[];
