extern const GeoLayout aq_mitruck_break_geo[];
extern u8 aq_mitruck_break_miu64_mi006_ci4[];
extern u8 aq_mitruck_break_miu64_mi006_pal_rgba16[];
extern u8 aq_mitruck_break_pum32_1_ci8[];
extern u8 aq_mitruck_break_pum32_1_pal_rgba16[];
extern u8 aq_mitruck_break_miu64_loco005_ci4[];
extern u8 aq_mitruck_break_miu64_loco005_pal_rgba16[];
extern Vtx aq_mitruck_break_aq_mitruck_break_mesh_layer_1_vtx_0[8];
extern Vtx aq_mitruck_break_aq_mitruck_break_mesh_layer_1_vtx_1[34];
extern Vtx aq_mitruck_break_aq_mitruck_break_mesh_layer_1_vtx_2[64];
extern Gfx aq_mitruck_break_aq_mitruck_break_mesh_layer_1[];
