extern const GeoLayout cct_goaldoor_breaka_geo[];
extern u8 cct_goaldoor_breaka_dz_cc_goaldoor_mecha128_ci4[];
extern u8 cct_goaldoor_breaka_dz_cc_goaldoor_mecha128_pal_rgba16[];
extern Vtx cct_goaldoor_breaka_cct_goaldoor_breaka_mesh_layer_1_vtx_0[16];
extern Gfx cct_goaldoor_breaka_cct_goaldoor_breaka_mesh_layer_1[];
