extern const GeoLayout mh_area_1_geo[];
extern const GeoLayout mh_area_1[];
extern const Collision mh_area_1_collision[];
extern const MacroObject mh_area_1_macro_objs[];
extern const Trajectory mh_area_1_spline_1089_object_00BE4D68_001[];
extern const Trajectory mh_area_1_spline_1089_object_00BE4D68_002[];
extern const Trajectory mh_area_1_spline_NurbsCurve[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_001[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_002[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_003[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_004[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_011[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_012[];
extern const Trajectory mh_area_1_spline_NurbsCurve_Spring_013[];
extern const GeoLayout mh_area_2_geo[];
extern const GeoLayout mh_area_2[];
extern const Collision mh_area_2_collision[];
extern const MacroObject mh_area_2_macro_objs[];
extern const Trajectory mh_area_2_spline_NurbsCurve_Spring_005[];
extern const Trajectory mh_area_2_spline_NurbsCurve_Spring_006[];
extern const Trajectory mh_area_2_spline_NurbsCurve_Spring_007[];
extern const Trajectory mh_area_2_spline_NurbsCurve_Spring_008[];
extern const GeoLayout mh_area_3_geo[];
extern const GeoLayout mh_area_3[];
extern const Collision mh_area_3_collision[];
extern const MacroObject mh_area_3_macro_objs[];
extern const Trajectory mh_area_3_spline_1088_object_00BC6BA0_002[];
extern const Trajectory mh_area_3_spline_1088_object_00BC6BA0_003[];
extern const Trajectory mh_area_3_spline_NurbsCurve_001[];
extern const Trajectory mh_area_3_spline_NurbsCurve_002[];
extern const Trajectory mh_area_3_spline_NurbsCurve_Spring_009[];
extern const Trajectory mh_area_3_spline_NurbsCurve_Spring_010[];
extern const GeoLayout mh_area_4_geo[];
extern const GeoLayout mh_area_4[];
extern const Collision mh_area_4_collision[];
extern const MacroObject mh_area_4_macro_objs[];
extern Vtx mh_dl_a3_001_mesh_layer_1_vtx_0[24];
extern Gfx mh_dl_a3_001_mesh_layer_1_tri_0[];
extern Vtx mh_dl_a3_002_mesh_layer_1_vtx_0[24];
extern Gfx mh_dl_a3_002_mesh_layer_1_tri_0[];
extern Vtx mh_dl_a3_003_mesh_layer_1_vtx_0[24];
extern Gfx mh_dl_a3_003_mesh_layer_1_tri_0[];
extern Vtx mh_dl_a3_004_mesh_layer_1_vtx_0[24];
extern Gfx mh_dl_a3_004_mesh_layer_1_tri_0[];
extern Gfx mat_mh_dl_f3dlite_material_002[];
extern Gfx mat_revert_mh_dl_f3dlite_material_002[];
extern Gfx mh_dl_a3_001_mesh_layer_1[];
extern Gfx mh_dl_a3_002_mesh_layer_1[];
extern Gfx mh_dl_a3_003_mesh_layer_1[];
extern Gfx mh_dl_a3_004_mesh_layer_1[];
