extern const GeoLayout pl_bombe_break_geo[];
extern u8 pl_bombe_break_miu64_ig011_ci4[];
extern u8 pl_bombe_break_miu64_ig011_pal_rgba16[];
extern u8 pl_bombe_break_miu64_ig006_ci4[];
extern u8 pl_bombe_break_miu64_ig006_pal_rgba16[];
extern Vtx pl_bombe_break_pl_bombe_break_mesh_layer_1_vtx_cull[8];
extern Vtx pl_bombe_break_pl_bombe_break_mesh_layer_1_vtx_0[32];
extern Gfx pl_bombe_break_pl_bombe_break_mesh_layer_1_tri_0[];
extern Vtx pl_bombe_break_pl_bombe_break_mesh_layer_1_vtx_1[20];
extern Gfx pl_bombe_break_pl_bombe_break_mesh_layer_1_tri_1[];
extern Gfx mat_pl_bombe_break_BOMBE_BREAKA_sa2mdl_0_f3d[];
extern Gfx mat_revert_pl_bombe_break_BOMBE_BREAKA_sa2mdl_0_f3d[];
extern Gfx mat_pl_bombe_break_BOMBE_BREAKA_sa2mdl_1_f3d[];
extern Gfx mat_revert_pl_bombe_break_BOMBE_BREAKA_sa2mdl_1_f3d[];
extern Gfx pl_bombe_break_pl_bombe_break_mesh_layer_1[];
